Best of
dailypenn/projects.thedp.com pull request #22
Opened 2021-01-20 04:15 UTC by CalvinHu73

2021-01-20 15:03 UTC, sigmachirality requested changes
Really liked the shared components and glad to see you've implemented the fonts like we talked about. Main thing for you to fix rn if you can/work on:

Descriptive component naming. Not everything is a wrapper: when you make a wrapper, you're either adding styles to the component you're wrapping or moving/spacing/laying out the components inside it. Wrapper is a catch-all term, but because it's a catch-all it's not descriptive, which makes it hard to grok what a component does immediately. If you can, rename wrapper components to be Layout, Style, Border, Spacer, etc components. Descriptive component naming saves lives and time!

2021-01-20 15:03 UTC, sigmachirality commented on src/pages/2021/best-of-penn/index.js
> +  const data = useStaticQuery(graphql`
this looks a bit fugly, but run prettier and see what it makes of it, and then defer to that.

2021-01-20 15:03 UTC, sigmachirality commented on src/pages/2021/best-of-penn/index.js
> +      <BlueComponent section={sections[5]}/>
prefer you to destructure this out using an array destructure above, something like const [first, second, third, fourth ... ] should work

2021-01-20 15:03 UTC, sigmachirality commented on src/styles/index.css
>  html {
delete dis

2021-01-20 15:03 UTC, sigmachirality commented on src/utils/font.js
>  `
enforce eof lines

2021-01-20 22:38 UTC, sigmachirality requested changes
Looking good my man, just some more fixes and we should be gtg

2021-01-20 22:38 UTC, sigmachirality commented on src/components/2021/best-of-penn/BlueComponent.js
> +export default BlueComponent
Calling a component "Component" generally means that they're general or HOC (something like PureComponent, for example). Can you make the name of this component any more general?

2021-01-20 22:38 UTC, sigmachirality commented on src/components/2021/best-of-penn/BlueComponent.js
> +const BlueCardWrapper = s(CardWrapper)`
bump

2021-01-20 22:38 UTC, sigmachirality commented on src/components/2021/best-of-penn/BlueComponent.js
> +const BlueCardWrapper = s(CardWrapper)`
BlueCardWrapper, CardWrapper, etc still named Wrapper and I think there's better possible names for them :(

2021-01-20 22:38 UTC, sigmachirality commented on src/components/shared/Navbar.js
> +  }
use a default destructor value, like ({ bgColor = "#FFFFFF" ...

2021-01-20 22:38 UTC, sigmachirality commented on src/components/shared/Navbar.js
> +                <NavText font={font} style={{color: fontColor}}> {text} </NavText>
Would prefer color as a prop like font or font as an inline style, but not both

2021-01-20 22:38 UTC, sigmachirality commented on src/components/shared/Navbar.js
> +          <Image src={img ? img : '/img/DP-Logo-Full.png'} className="img-fluid" />
also can use a default value in the destructure for this

2021-01-20 22:38 UTC, sigmachirality commented on src/components/shared/Navbar.js
> +                <NavText font={font} style={{color: fontColor}}> {text} </NavText>
same as line 71

2021-01-20 22:38 UTC, sigmachirality commented on src/components/shared/Footer.js
> +export const Footer = ({ font, emoji, bgColor, fontColor, year }) => (
you can use a default value here instead of casing on the truthy value of year I think

2021-01-20 22:38 UTC, sigmachirality commented on src/components/2021/best-of-penn/BlueComponent.js
> +      )}
destructure this above (I'm not going to point out every case of a systematic error when it happens, just one)

2021-01-20 22:38 UTC, sigmachirality commented on src/components/2021/best-of-penn/TanComponent.js
> +const Card = ({ item }) => (
destructure item further

2021-01-20 22:38 UTC, sigmachirality commented on src/components/2021/best-of-penn/TanComponent.js
> +const TanComponent = ({ section, colmd }) => (
destructure section or maybe even take section props as seperate props i.e. ({ section, description, items ... })

2021-01-20 22:38 UTC, sigmachirality commented on src/pages/2021/best-of-penn/index.js
> +const navBarTitles = {
Since this a const use snakecase+capitalize (NAVBAR_TITLES)

2021-01-20 22:39 UTC, peterbaile requested changes
fix changes

2021-01-20 22:39 UTC, peterbaile commented on src/components/shared/Navbar.js
> +  if (!bgColor) {
this is not the right way of using optional parameters, check this out https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters. In other words, it sld be `bgColor='#FFFFFF'` on line 46

2021-01-20 22:39 UTC, peterbaile commented on src/components/shared/Navbar.js
> +  if (!fontColor) {
same here

2021-02-07 18:11 UTC, peterbaile approved these changes

2021-02-07 18:11 UTC, merged